King Xiong/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace King_Xiong.Models
{
    public class BlogPost
    {
        //constructor has the same name as its class
        //initializes an object of that type
        public BlogPost()
        {
            //'this' refers to the comment coming from Icollection<Comment> 

           this.Comments = new HashSet<Comment>();
        }
        public int Id { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset Created { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset? Updated { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        [AllowHtml]
        public string Body { get; set; }
        public string MediaURL { get; set; }
        public bool Published { get; set; }

        //navigation property
        //In this scenerio, collection is a list of 'generic'Comment  object 
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

King Xiong/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using King_Xiong.Models;
using King_Xiong.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace King_Xiong.Controllers
{
    [RequireHttps]
    public class BlogPostsController : UserController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        //public ActionResult Index(int? page)
        //{
        //    int pageSize = 6; // display three blog post at a time before returning the view
        //    int pageNumber = (page ?? 1);

        //    var posts = db.Posts.OrderBy(p => p.Created).ToPagedList(pageNumber, pageSize);
        //    return View(posts);
        //}

        public ActionResult AdIndex(int? page, string searchStr)
        {
                ViewBag.Search = searchStr;
                var blogList = IndexSearch(searchStr);

                int pageSize = 3; // display three blog post at a time before returning the view
                int pageNumber = (page ?? 1);


                return View(blogList.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 3; // display three blog post at a time before returning the view
            int pageNumber = (page ?? 1);


            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Search(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 3; // display three blog post at a time before returning the view
            int pageNumber = (page ?? 1);


            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;
            if (searchStr != null)
            {
                result = db.Posts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStr) || p.Body.Contains(searchStr) ||
                                                        p.Comments.Any(c => c.Body.Contains(searchStr) ||
                                                        c.Author.FirstName.Contains(searchStr) ||
                                                        c.Author.LastName.Contains(searchStr) ||
                                                        c.Author.DisplayName.Contains(searchStr) ||
                                                        c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.Posts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(String slug)
        {
            if (String.IsNullOrWhiteSpace(slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }



                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5 
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string slug)
        {
            if (String.IsNullOrWhiteSpace(slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Created,Updated,Title,Slug,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var editSlug = StringUtilities.URLFriendly(blogPost.Title);
                //var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (db.Posts.Any((p => p.Title == blogPost.Title && p.Id != blogPost.Id)))
                {
                    ModelState.AddModelError("Title", "The title must be uinque.");
                    return View(blogPost);
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }
                //if (String.IsNullOrWhiteSpace(Slug))
                //{
                //    ModelState.AddModelError("Title", "Invalid Title");
                //    return View(blogPost);
                //}
                //if (db.Posts.Any(p => p.Slug == Slug))
                //{
                //    ModelState.AddModelError("Title", "The title must be unique");
                //    return View(blogPost);
                //}
                blogPost.Slug = editSlug;
                //blogPost.Slug = Slug;
                blogPost.Updated = DateTimeOffset.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

King Xiong/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using King_Xiong.Models;
using Microsoft.AspNet.Identity;

namespace King_Xiong.Controllers
{
    [RequireHttps]
    public class CommentsController : UserController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Author).Include(c => c.Post);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5

        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);

        }
        // GET: Comments/Create

        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PostId,AuthorId,Created,Body")] Comment comment)
        {

            if (ModelState.IsValid)
            {
                comment.AuthorId = User.Identity.GetUserId(); //adds using Microsoft.AspNet.Identity; 
                comment.Created = new DateTimeOffset(DateTime.Now);
                db.Comments.Add(comment);
                db.SaveChanges();
                var thisPost = db.Posts.Find(comment.PostId);
                if (thisPost != null)
                {
                    return RedirectToAction("Details", "BlogPosts", new { slug = thisPost.Slug });// redirect to details page in Blog Post. 
                }

            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorId);
            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);

            return View(comment);

        }
        // GET: Comments/Edit/5


        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(string slug, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            //ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorId);
            ViewBag.Slug = slug;
            return View(comment);
        }


        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit([Bind(Include = "Id,PostId,AuthorId,Body,Created,Updated,UpdateReason")] Comment comment, string PostSlug)
        {

            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(PostSlug))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var post = db.Posts.FirstOrDefault(p => p.Slug == PostSlug);
                if (post == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    // look up post so that I can get the ID to set the PostID of the comment
                    comment.PostId = post.Id;

                    var userId = User.Identity.GetUserId();
                    comment.AuthorId = userId;
                    comment.Updated = DateTimeOffset.Now;

                    db.Entry(comment).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Details", "Blog", new { slug = post.Slug });
                }
            }
            //ViewBag.AuthorId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorId);
            //ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult DeleteConfirmed(int id)
        {
            var sameUser = User.Identity.GetUserId();
            Comment comment = db.Comments.Find(id);
            var slug = comment.Post.Slug;
            // comment.slug is deleted here but to save it's string value, we called it above,
            // that's why when we used it in the slug, it didnt work because
            // return RedirectToAction("Details", "BlogPosts", new { slug = comment.post.slug});
            // comment.post.slug does not exist after we remove it using the db.Comments.Remove(comment)
            // this 'comment' does not exist in the db, therefore we cannot find redirect to comment.post.slug afterwards
 
            db.Comments.Remove(comment);
            db.SaveChanges();



            //var commentPost = db.Posts.Find(comment.PostId);
            //if (commentPost != null)
            //{
            //return RedirectToAction("Index");

            // domain.com/blogposts/details/[slug = blogpost.title]
            return RedirectToAction("Details", "BlogPosts", new { slug = slug });

            //}
            //return View(comment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

King Xiong/Views/BlogPosts/AdIndex.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<King_Xiong.Models.BlogPost>

@{
    ViewBag.Title = "AdIndex";
}

 
@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <div class="container">
            <br />
            <div class="floatLeft">
                <a class="btn btn-outline" href="@Url.Action("Create", "BlogPosts")"><i class="fa fa-plus"></i>Create New</a>
                <a class="btn btn-outline" href="@Url.Action("Index", "BlogPosts")"><i class="fa fa-table"></i>Blog Index</a>
            </div>

            <div class="floatRight">
                @using (Html.BeginForm("Index", "BlogPosts", FormMethod.Get, htmlAttributes: new { @class = "form" }))
                {
                    <div class="controls controls-row search-row">
                        <input style="height: 34px" id="searchStr" name="searchStr" class="input-block-level" type="text" placeholder="Search" />
                        <button style="margin-top: -3px" id="searchStr" name="searchStr" class="btn btn-info" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                }
            </div>
            <h2 class="text-center">Admin Index</h2>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Created)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Updated)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Slug)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Body)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].MediaURL)
                    </th>
                    <th>
                        Functions
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model[0].Published)
                        </th>
                        <th></th>*@
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Created)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Updated)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Slug)
                        </td>
                        <td>
                            @Html.Raw(item.Body)
                            @*@Html.DisplayFor(modelItem => item.Body)*@
                        </td>
                        <td>
                            @if (item.MediaURL != null)
                            {
                                <img class="img-responsive previewImage" src="@item.MediaURL" alt="" />
                            }
                            @*@Html.DisplayFor(modelItem => item.MediaURL)*@
                        </td>
                        @*<td>
                                @Html.DisplayFor(modelItem => item.Published)
                            </td>*@

                        <td>
                            <a href="@Url.Action("Edit", "BlogPosts", new { slug = item.Slug })" class="btn btn-outline text-center" style="width:109.45px"><i class="fa fa-edit"></i>Edit</a>
                            <a href="@Url.Action("Details", "BlogPosts", new { slug = item.Slug })" class="btn btn-outline text-center"><i class="fa fa-table"></i>Details</a>
                            <a href="@Url.Action("Delete", "BlogPosts", new { id = item.Id })" class="btn btn-outline text-center" style="width:109.45px"><i class="fa fa-trash"></i>Delete</a>
                            @*@Html.ActionLink(linkText: "Edit", actionName: "Edit", controllerName: "BlogPosts", routeValues: new { slug = item.Slug }, htmlAttributes: "")<br />
                            @Html.ActionLink(linkText: "Details", actionName: "Details", controllerName: "BlogPosts", routeValues: new { slug = item.Slug }, htmlAttributes: "")<br />
                            @Html.ActionLink(linkText: "Delete", actionName: "Delete", controllerName: "BlogPosts", routeValues: new { id = item.Id }, htmlAttributes: "")*@
                        </td>
                    </tr>
                }
            </table>

            @*ORIGINAL PAGINATION CONTROL
                <div style="text-align: center">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>*@

            <div style="text-align: center">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount @Html.PagedListPager(Model, page => Url.Action("AdIndex", new { page, searchStr = ViewBag.Search }))
            </div>
        </div>
    }
}

King Xiong/Views/BlogPosts/Create.cshtml
@model King_Xiong.Models.BlogPost

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm("Create", "BlogPosts", FormMethod.Post, new { enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="container form-horizontal">
        <h2 class="text-center">Create BlogPost</h2>
      
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MediaURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="image" type="file" class="form-control" id="fileUpload" />
                @*@Html.EditorFor(model => model.MediaURL, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.MediaURL, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-block" style="width:109.45px"/>
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","BlogPosts")" class="btn btn-outline"><i class="fa fa-list"></i>Back To List</a>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>
@section scripts
    {
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript">
        $(function () {
            tinymce.init({
               selector: '#Body'
            });
        });
    </script>
}

King Xiong/Views/BlogPosts/Details.cshtml
@using Microsoft.AspNet.Identity;
@model King_Xiong.Models.BlogPost

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2>@Html.DisplayFor(m => m.Title)</h2>
        </div>
        <div class="col-md-12 text-right">
            <p>Date: @Model.Created.ToString("MM/dd/yyyy")</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-5">
            @if (Model.MediaURL != null)
            {
                <img class="center-block img-responsive" src="@Model.MediaURL" alt="" width="55%" />
            }
        </div>
        <div class="col-md-7">
                @Html.Raw(Model.Body)
        </div>
    </div>

    <div class="row">
        <br />
        
        <h2 class="text-center">Comments</h2>
        <div class="col-md-12">
            @* Model.Comments - collection of comments in the Model named Comments that is in a BlogPosts*@
            @* var comment in Model.Comments - a single comment "object" thats has been pulled out from Model.comment*@
            @* foreach loop - for each number of blogpost comments*@
            @foreach (var comment in Model.Comments)
            {
                var sameUser = User.Identity.GetUserId();
                //From the list,  we are grabbing every 'Comments'
                <div style="border:solid; border-color:black; width: 700px; height: auto">
                    @if (comment.Author.DisplayName != null)
                    {
                        <div>
                            <div style="font-size:24px"><text>&nbsp;</text>@comment.Author.DisplayName</div>
                            <div style="font-size:10px"><text>&nbsp;</text>@comment.Created.ToString("MM/dd/yyyy")</div>
                        </div>
                    }
                    else
                    {
                            <h3>@comment.Author.Email</h3>
                            <h5>@comment.Created.ToString("MM/dd/yyyy")</h5>
                    }

                    <h3>@Html.Raw(comment.Body)</h3>
                </div>
                if (Request.IsAuthenticated)
                {
                    if (User.IsInRole("Admin") || User.IsInRole("Moderator") || sameUser == comment.AuthorId)
                    {
                        <a href="@Url.Action("Edit", "Comments", new { slug = Model.Slug, id = comment.Id})" class="btn btn-outline"><i class="fa fa-edit"></i> Edit Comment</a>
                        <a href="@Url.Action("Delete", "Comments", new { slug = Model.Slug, id = comment.Id})" class="btn btn-outline"><i class="fa fa-trash"></i> Delete Comment</a>                                            
                    }
                }
            }
            @* This is a form we use to create a comment by accessing the "create" actionresult from the "comments" controller  *@
            <div class="container comment-form text-center">
                @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
                {
                    if (Request.IsAuthenticated)
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="PostId" value="@Model.Id" />
                        <div class="form-group ">
                            <label for="comment-new_textarea" class="sr-only">Enter your comment</label>
                            <textarea class="form-control comment-form text-center" rows="2" id="body" name="body" placeholder="Comment Post"></textarea>
                        </div>
                        <button type="submit" class="btn btn-outline">Comment</button>
                        <br />
                        <br />
                        <br />
                    }
                }
            </div>
        </div>
    </div>
    <div class="text-center">
        @if (Request.IsAuthenticated)
        {
            if (User.IsInRole("Admin"))
            {
                <a href="@Url.Action("AdIndex", "BlogPosts")" class="btn btn-outline" style="width: 150px"><i class="fa fa-table"></i>Admin Index</a>
                <a href="@Url.Action("Edit", "BlogPosts", new { slug = Model.Slug})" class="btn btn-outline" style="width: 150px"><i class="fa fa-edit"></i>Edit </a>
            }
            <a href="@Url.Action("Index", "BlogPosts", new { slug = Model.Slug})" class="btn btn-outline"><i class="fa fa-sign-out"></i>Back to List</a>
        }
    </div>
</div>
<br>
<br>
<br>
<br>