King Xiong/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using King_Xiong.Models;
using King_Xiong.Helpers;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace King_Xiong.Controllers
{
    [RequireHttps]
    public class BlogPostsController : UserController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        //public ActionResult Index(int? page)
        //{
        //    int pageSize = 6; // display three blog post at a time before returning the view
        //    int pageNumber = (page ?? 1);

        //    var posts = db.Posts.OrderBy(p => p.Created).ToPagedList(pageNumber, pageSize);
        //    return View(posts);
        //}

        public ActionResult AdIndex(int? page, string searchStr)
        {
                ViewBag.Search = searchStr;
                var blogList = IndexSearch(searchStr);

                int pageSize = 3; // display three blog post at a time before returning the view
                int pageNumber = (page ?? 1);


                return View(blogList.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 3; // display three blog post at a time before returning the view
            int pageNumber = (page ?? 1);


            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Search(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 3; // display three blog post at a time before returning the view
            int pageNumber = (page ?? 1);


            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;
            if (searchStr != null)
            {
                result = db.Posts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStr) || p.Body.Contains(searchStr) ||
                                                        p.Comments.Any(c => c.Body.Contains(searchStr) ||
                                                        c.Author.FirstName.Contains(searchStr) ||
                                                        c.Author.LastName.Contains(searchStr) ||
                                                        c.Author.DisplayName.Contains(searchStr) ||
                                                        c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.Posts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(String slug)
        {
            if (String.IsNullOrWhiteSpace(slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blogPost);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }



                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.Posts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5 
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string slug)
        {
            if (String.IsNullOrWhiteSpace(slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.FirstOrDefault(p => p.Slug == slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Created,Updated,Title,Slug,Body,MediaURL,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var editSlug = StringUtilities.URLFriendly(blogPost.Title);
                //var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (db.Posts.Any((p => p.Title == blogPost.Title && p.Id != blogPost.Id)))
                {
                    ModelState.AddModelError("Title", "The title must be uinque.");
                    return View(blogPost);
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }
                //if (String.IsNullOrWhiteSpace(Slug))
                //{
                //    ModelState.AddModelError("Title", "Invalid Title");
                //    return View(blogPost);
                //}
                //if (db.Posts.Any(p => p.Slug == Slug))
                //{
                //    ModelState.AddModelError("Title", "The title must be unique");
                //    return View(blogPost);
                //}
                blogPost.Slug = editSlug;
                //blogPost.Slug = Slug;
                blogPost.Updated = DateTimeOffset.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.Posts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            //model to view 
            //data sent to view to be render
            //data being sent back to the viewer
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.Posts.Find(id);
            db.Posts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

King Xiong/Controllers/HomeController.cs
using King_Xiong.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace King_Xiong.Controllers

{   [RequireHttps]
    public class HomeController : UserController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "About Me";

            return View();
        }
        //must leave contact on to view the page Contact
        public ActionResult Contact()
        {
            ViewBag.Message = "Contact";

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    var body = "<p>Email From: <b>{0}</b>({1})</p><p>Message:</p><p>{2}</p>";
                    //model.Body = "This is a message from your personal site. The name and the email of the contacting person is above";
                    var email = new MailMessage(ConfigurationManager.AppSettings["username"], ConfigurationManager.AppSettings["emailTo"])
                    {
                        Subject = "Welcome to kingCom",
                        Body = string.Format(body, model.FromName, model.FromEmail, model.Body),
                        IsBodyHtml = true
                    };

                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);

                    return RedirectToAction("Sent");

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }

            }

            return View(model);
        }

        public ActionResult Portfolio()
        {
            ViewBag.Message = "Portfolio";

            return View();
        }
        public ActionResult Blog()
        {
            ViewBag.Message = "Blog";

            return View();
        }

        public ActionResult Sent()
        {
            return View();
        }
    }
}

King Xiong/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

King Xiong/Views/Home/Contact.cshtml
@model King_Xiong.Models.EmailModel
<div class="container">
    <br />
    @using (Html.BeginForm("Contact", "Home", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <h2 class="text-center">Send me a message. </h2>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.FromName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FromName, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.FromName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.FromEmail, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control", placeholder = "example@email.com" })
                @Html.ValidationMessageFor(m => m.FromEmail)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject Line" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Body, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Body, new { @class = "form-control", placeholder = "Body" })
                @Html.ValidationMessageFor(m => m.Body)<p></p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <p>
                <input type="submit" class="btn btn-primary" value="Send" />
                </p>
            </div>
        </div>
    }

        @{
            ViewBag.Title = "Contact";
        }
    </div>

King Xiong/Views/Home/Index.cshtml
<body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top"><i class="fa fa-home"></i>Home</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#portfolio"><i class="fa fa-calculator"></i>Portfolio </a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#blog"><i class="fa fa-binoculars"></i>Blog</a>
                    </li>
                    <li>
                        <a href="https://kxiong-bugtracker.azurewebsites.net" target="_blank"><i class="fa fa-bug"></i>Bugtracker</a>
                    </li>
                    <li>
                        <a href="https://kxiong-budgeter.azurewebsites.net" target="_blank"><i class="fa fa-dollar"></i>Budgeter</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact"><i class="fa fa-address-book"></i>Contact</a>
                    </li>
                    <li>
                        @Html.Partial("_LoginPartial")
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="header-content">
                        <div class="header-content-inner text-center">
                            <div style="font-size: 60px">My name is <br/>King Xiong</div>
                            <h3>I graduated at the University of North Carolina at Charlotte in 2014 looking for a career opportunity in web development. I am a highly-motivated self-starter that is looking ot use my education and training to further advance my career. My background includes strong analytics and business analysis driven from proper education training and years of experience in my family business. Given the right entry level opportunity, I am prepared to do what it takes to succeed in this position.</h3>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="header-content">
                        <div class="header-content-inner">
                            <img src="~/Library/Template/img/IMG_King Xiong(C).jpg" class="img-responsive" style="max-height: 658px; border: 3px solid; border-color:black; border-radius: 100px" />
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <p style="font-size:48px"><i class="fa fa-hand-o-down"></i> More below</p>
                </div>
            </div>
        </div>
    </header>
    <header id="portfolio" class="bg-primary text-center">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="header-content">
                        <div class="header-content-inner text-center">
                            <h3>I created a personal portfolio and blog website using C#, MVC5 and JavaScript. Check out my portfolio to see the implications of Html5, Javascripts, and CSS.</h3>
                            <a href="@Url.Action("Portfolio", "Home")" class="btn btn-outline btn-xl page-scroll">Check out my portfolio</a><br />
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="header-content">
                        <div class="header-content-inner">
                            <img src="~/Library/Template/img/Magic.JPG" class="img-responsive" style="width: auto; height: 480px ; border: 3px solid; border-color:greenyellow; border-radius: 50px" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <p style="font-size:48px"><i class="fa fa-hand-o-down"></i> More <i class="fa fa-hand-o-down"></i> More! <i class="fa fa-hand-o-down"></i> More!!</p>
            </div>
        </div>
    </header>
    <header id="blog" class="features cta bg-primary1 h3a" style="background-color:darkblue">
            <div class="container">
                <div class="col-sm-4" >
                    <div class="header-content">
                        <div class="header-content-inner">
                            <h3>Check out my blog. Using JavaScript, C#, and MVC5, I created a blog. Also, I implemented CSS, HTML5, and JavaScript with this blog. Feel free to read about my adventures. </h3>
                            <a href="@Url.Action("Index", "BlogPosts")" class="btn btn-outline btn-xl page-scroll">Check out my blog</a><br />
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="header-content">
                        <div class="header-content-inner">                            
                                <img src="~/Library/Template/img/Mountain_View.jpg" class="img-responsive" style="width: auto; border: 3px solid; border-color:greenyellow; border-radius: 50px" />
                            </div>
                        </div>
                    </div>
                <div class="row text-center">
                    <p style="font-size:48px"><i class="fa fa-hand-o-down"></i> Feel Free to contact me</p>
                </div>
                </div>
</header>
    <section id="contact" class="contact bg-primary">
        <div class="container">
            <h1>Questions? Let me hear about it.</h1>
            <h2>I <i class="fa fa-heart"></i> new friends!</h2>
            <a href="@Url.Action("Contact", "Home")" class="btn btn-outline btn-xl">Contact Me!</a>
        </div>
        <div class="container">
            <br />
            <br />
            <br/>
            <br />
            <h1>Here is my resume.<br /> Feel free to read about my experience.</h1>
            <a href="~/Library/Template/img/King_Xiong-Resume.pdf" class="btn btn-outline btn-xl">Resume</a>
        </div>
    </section>
    <footer>
        <div class="container">
            <p>&copy; King Xiong 2017</p>
        </div>
    </footer>

</body>

King Xiong/Views/Home/Sent.cshtml
@{
    ViewBag.Title = "Sent";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>The email was sent successfully.</p>